In [6]:
simbolo = ['IFNG','Il10','Tnf','CSF2']
full_name = [
    'interferon gamma',
    'interleukin 10',
    'tumor necrosis factor',
    'colony stimulating factor 2'
]
source = ['HGNC:HGNC:5438','RGD:2886','MGI:MGI:104798','HGNC:HGNC:2434']
gene_type = ['protein coding','protein coding','protein coding','protein coding']
organism = ['Homo sapiens','Rattus norvegicus','Mus musculus','Homo sapiens']
chromosome = [12,13,17,5]

In [7]:
gene_matriz_lista = [
    simbolo,
    full_name,
    source,
    gene_type,
    organism,
    chromosome
]
gene_matriz_lista

[['IFNG', 'Il10', 'Tnf', 'CSF2'],
 ['interferon gamma',
  'interleukin 10',
  'tumor necrosis factor',
  'colony stimulating factor 2'],
 ['HGNC:HGNC:5438', 'RGD:2886', 'MGI:MGI:104798', 'HGNC:HGNC:2434'],
 ['protein coding', 'protein coding', 'protein coding', 'protein coding'],
 ['Homo sapiens', 'Rattus norvegicus', 'Mus musculus', 'Homo sapiens'],
 [12, 13, 17, 5]]

In [8]:
gene_matriz_disc = {
    'Símbolos': simbolo,
    'Nomes completos': full_name,
    'Origem': source,
    'Tipo': gene_type,
    'Organismo': organism,
    'Cromossomo': chromosome
}
gene_matriz_disc

{'Símbolos': ['IFNG', 'Il10', 'Tnf', 'CSF2'],
 'Nomes completos': ['interferon gamma',
  'interleukin 10',
  'tumor necrosis factor',
  'colony stimulating factor 2'],
 'Origem': ['HGNC:HGNC:5438', 'RGD:2886', 'MGI:MGI:104798', 'HGNC:HGNC:2434'],
 'Tipo': ['protein coding',
  'protein coding',
  'protein coding',
  'protein coding'],
 'Organismo': ['Homo sapiens',
  'Rattus norvegicus',
  'Mus musculus',
  'Homo sapiens'],
 'Cromossomo': [12, 13, 17, 5]}

In [9]:
gene_matriz_disc['Símbolos']

['IFNG', 'Il10', 'Tnf', 'CSF2']

In [10]:
gene_matriz_disc['Cromossomo']

[12, 13, 17, 5]

In [14]:
simbolo.append('Il6')
simbolo

['IFNG', 'Il10', 'Tnf', 'CSF2', 'Il6']

In [17]:
gene_matriz_disc['Símbolos']

['IFNG', 'Il10', 'Tnf', 'CSF2', 'Il6']

In [18]:
simbolo.insert(1, 'IFNB')
gene_matriz_disc['Símbolos']

['IFNG', 'IFNB', 'Il10', 'Tnf', 'CSF2', 'Il6']

In [19]:
simbolo.remove('IFNB')
gene_matriz_disc['Símbolos']

['IFNG', 'Il10', 'Tnf', 'CSF2', 'Il6']

In [20]:
simbolo.pop()
gene_matriz_disc['Símbolos']

['IFNG', 'Il10', 'Tnf', 'CSF2']

In [21]:
import numpy as np

In [24]:
gene_matriz_lista

[['IFNG', 'Il10', 'Tnf', 'CSF2'],
 ['interferon gamma',
  'interleukin 10',
  'tumor necrosis factor',
  'colony stimulating factor 2'],
 ['HGNC:HGNC:5438', 'RGD:2886', 'MGI:MGI:104798', 'HGNC:HGNC:2434'],
 ['protein coding', 'protein coding', 'protein coding', 'protein coding'],
 ['Homo sapiens', 'Rattus norvegicus', 'Mus musculus', 'Homo sapiens'],
 [12, 13, 17, 5]]

In [29]:
gene_matriz_array = np.asarray(gene_matriz_lista)
gene_matriz_array

array([['IFNG', 'Il10', 'Tnf', 'CSF2'],
       ['interferon gamma', 'interleukin 10', 'tumor necrosis factor',
        'colony stimulating factor 2'],
       ['HGNC:HGNC:5438', 'RGD:2886', 'MGI:MGI:104798', 'HGNC:HGNC:2434'],
       ['protein coding', 'protein coding', 'protein coding',
        'protein coding'],
       ['Homo sapiens', 'Rattus norvegicus', 'Mus musculus',
        'Homo sapiens'],
       ['12', '13', '17', '5']], dtype='<U27')

In [35]:
gene_matriz_array[[0,2,-1]]

array([['IFNG', 'Il10', 'Tnf', 'CSF2'],
       ['HGNC:HGNC:5438', 'RGD:2886', 'MGI:MGI:104798', 'HGNC:HGNC:2434'],
       ['12', '13', '17', '5']], dtype='<U27')

In [45]:
gene_matriz_array[:,-1]

array(['CSF2', 'colony stimulating factor 2', 'HGNC:HGNC:2434',
       'protein coding', 'Homo sapiens', '5'], dtype='<U27')

In [47]:
gene_matriz_array[-1,:]

array(['12', '13', '17', '5'], dtype='<U27')

In [52]:
gene_matriz_array[[0,1],[3,0]]

array(['CSF2', 'interferon gamma'], dtype='<U27')

In [53]:
import pandas as pd

In [54]:
np.arange(4)

array([0, 1, 2, 3])

In [55]:
gene_matriz = pd.DataFrame(
    columns=np.arange(4),
    data=[simbolo, full_name, source, gene_type, organism, chromosome],
    index=[
            'Símbolos',
            'Nomes completo',
            'Origem',
            'Tipo',
            'Organismo',
            'Cromossomo'
    ]
)
gene_matriz

,0,1,2,3
Símbolos,IFNG,Il10,Tnf,CSF2
Nomes completo,interferon gamma,interleukin 10,tumor necrosis factor,colony stimulating factor 2
Origem,HGNC:HGNC:5438,RGD:2886,MGI:MGI:104798,HGNC:HGNC:2434
Tipo,protein coding,protein coding,protein coding,protein coding
Organismo,Homo sapiens,Rattus norvegicus,Mus musculus,Homo sapiens
Cromossomo,12,13,17,5

In [57]:
gene_matriz = gene_matriz.transpose()
gene_matriz

,Símbolos,Nomes completo,Origem,Tipo,Organismo,Cromossomo
0,IFNG,interferon gamma,HGNC:HGNC:5438,protein coding,Homo sapiens,12
1,Il10,interleukin 10,RGD:2886,protein coding,Rattus norvegicus,13
2,Tnf,tumor necrosis factor,MGI:MGI:104798,protein coding,Mus musculus,17
3,CSF2,colony stimulating factor 2,HGNC:HGNC:2434,protein coding,Homo sapiens,5

In [58]:
gene_matriz.set_index('Símbolos', inplace=True)
gene_matriz

,Nomes completo,Origem,Tipo,Organismo,Cromossomo
Símbolos,,,,,
IFNG,interferon gamma,HGNC:HGNC:5438,protein coding,Homo sapiens,12
Il10,interleukin 10,RGD:2886,protein coding,Rattus norvegicus,13
Tnf,tumor necrosis factor,MGI:MGI:104798,protein coding,Mus musculus,17
CSF2,colony stimulating factor 2,HGNC:HGNC:2434,protein coding,Homo sapiens,5

In [60]:
gene_matriz_lista = pd.DataFrame(gene_matriz_lista)
gene_matriz_lista

,0,1,2,3
0,IFNG,Il10,Tnf,CSF2
1,interferon gamma,interleukin 10,tumor necrosis factor,colony stimulating factor 2
2,HGNC:HGNC:5438,RGD:2886,MGI:MGI:104798,HGNC:HGNC:2434
3,protein coding,protein coding,protein coding,protein coding
4,Homo sapiens,Rattus norvegicus,Mus musculus,Homo sapiens
5,12,13,17,5

In [62]:
gene_matriz_lista = gene_matriz_lista.T
gene_matriz_lista

,0,1,2,3,4,5
0,IFNG,interferon gamma,HGNC:HGNC:5438,protein coding,Homo sapiens,12
1,Il10,interleukin 10,RGD:2886,protein coding,Rattus norvegicus,13
2,Tnf,tumor necrosis factor,MGI:MGI:104798,protein coding,Mus musculus,17
3,CSF2,colony stimulating factor 2,HGNC:HGNC:2434,protein coding,Homo sapiens,5

In [63]:
gene_matriz_lista.set_index(0, inplace=True)
gene_matriz_lista

,1,2,3,4,5
0,,,,,
IFNG,interferon gamma,HGNC:HGNC:5438,protein coding,Homo sapiens,12
Il10,interleukin 10,RGD:2886,protein coding,Rattus norvegicus,13
Tnf,tumor necrosis factor,MGI:MGI:104798,protein coding,Mus musculus,17
CSF2,colony stimulating factor 2,HGNC:HGNC:2434,protein coding,Homo sapiens,5

In [70]:
gene_matriz_lista.columns = ['Nomes completo','Origem','Tipo','Organismo','Cromossomo']
gene_matriz_lista

,Nomes completo,Origem,Tipo,Organismo,Cromossomo
0,,,,,
IFNG,interferon gamma,HGNC:HGNC:5438,protein coding,Homo sapiens,12
Il10,interleukin 10,RGD:2886,protein coding,Rattus norvegicus,13
Tnf,tumor necrosis factor,MGI:MGI:104798,protein coding,Mus musculus,17
CSF2,colony stimulating factor 2,HGNC:HGNC:2434,protein coding,Homo sapiens,5

In [73]:
gene_matriz_data = pd.DataFrame(gene_matriz_disc).set_index('Símbolos')
gene_matriz_data

,Nomes completos,Origem,Tipo,Organismo,Cromossomo
Símbolos,,,,,
IFNG,interferon gamma,HGNC:HGNC:5438,protein coding,Homo sapiens,12
Il10,interleukin 10,RGD:2886,protein coding,Rattus norvegicus,13
Tnf,tumor necrosis factor,MGI:MGI:104798,protein coding,Mus musculus,17
CSF2,colony stimulating factor 2,HGNC:HGNC:2434,protein coding,Homo sapiens,5

In [75]:
gene_matriz_data['Origem']

Símbolos
IFNG    HGNC:HGNC:5438
Il10          RGD:2886
Tnf     MGI:MGI:104798
CSF2    HGNC:HGNC:2434
Name: Origem, dtype: object

In [78]:
gene_matriz_data[['Origem', 'Tipo']]

                  Origem            Tipo
Símbolos
IFNG      HGNC:HGNC:5438  protein coding
Il10            RGD:2886  protein coding
Tnf       MGI:MGI:104798  protein coding
CSF2      HGNC:HGNC:2434  protein coding

In [79]:
gene_matriz_data[['Tipo', 'Origem']]

                    Tipo          Origem
Símbolos
IFNG      protein coding  HGNC:HGNC:5438
Il10      protein coding        RGD:2886
Tnf       protein coding  MGI:MGI:104798
CSF2      protein coding  HGNC:HGNC:2434

In [81]:
gene_matriz_data.loc['IFNG']

Nomes completos    interferon gamma
Origem               HGNC:HGNC:5438
Tipo                 protein coding
Organismo              Homo sapiens
Cromossomo                       12
Name: IFNG, dtype: object

In [82]:
gene_matriz_data.loc[['Tnf', 'IFNG']]

,Nomes completos,Origem,Tipo,Organismo,Cromossomo
Símbolos,,,,,
Tnf,tumor necrosis factor,MGI:MGI:104798,protein coding,Mus musculus,17
IFNG,interferon gamma,HGNC:HGNC:5438,protein coding,Homo sapiens,12

In [84]:
gene_matriz_data.iloc[0]

Nomes completos    interferon gamma
Origem               HGNC:HGNC:5438
Tipo                 protein coding
Organismo              Homo sapiens
Cromossomo                       12
Name: IFNG, dtype: object

In [86]:
gene_matriz_data.iloc[[2,0]]

,Nomes completos,Origem,Tipo,Organismo,Cromossomo
Símbolos,,,,,
Tnf,tumor necrosis factor,MGI:MGI:104798,protein coding,Mus musculus,17
IFNG,interferon gamma,HGNC:HGNC:5438,protein coding,Homo sapiens,12

In [89]:
gene_matriz_data[['Tipo','Origem']].iloc[[2,0]]

                    Tipo          Origem
Símbolos
Tnf       protein coding  MGI:MGI:104798
IFNG      protein coding  HGNC:HGNC:5438

In [91]:
gene_matriz_data.iloc[:2]

,Nomes completos,Origem,Tipo,Organismo,Cromossomo
Símbolos,,,,,
IFNG,interferon gamma,HGNC:HGNC:5438,protein coding,Homo sapiens,12
Il10,interleukin 10,RGD:2886,protein coding,Rattus norvegicus,13

In [101]:
gene_matriz_data[gene_matriz_data['Cromossomo'] > 10]

,Nomes completos,Origem,Tipo,Organismo,Cromossomo
Símbolos,,,,,
IFNG,interferon gamma,HGNC:HGNC:5438,protein coding,Homo sapiens,12
Il10,interleukin 10,RGD:2886,protein coding,Rattus norvegicus,13
Tnf,tumor necrosis factor,MGI:MGI:104798,protein coding,Mus musculus,17

In [103]:
gene_matriz_data.head(2)

,Nomes completos,Origem,Tipo,Organismo,Cromossomo
Símbolos,,,,,
IFNG,interferon gamma,HGNC:HGNC:5438,protein coding,Homo sapiens,12
Il10,interleukin 10,RGD:2886,protein coding,Rattus norvegicus,13

In [105]:
gene_matriz_data.tail(2)

,Nomes completos,Origem,Tipo,Organismo,Cromossomo
Símbolos,,,,,
Tnf,tumor necrosis factor,MGI:MGI:104798,protein coding,Mus musculus,17
CSF2,colony stimulating factor 2,HGNC:HGNC:2434,protein coding,Homo sapiens,5

In [106]:
gene_matriz_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, IFNG to CSF2
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Nomes completos  4 non-null      object
 1   Origem           4 non-null      object
 2   Tipo             4 non-null      object
 3   Organismo        4 non-null      object
 4   Cromossomo       4 non-null      int64
dtypes: int64(1), object(4)
memory usage: 364.0+ bytes

In [107]:
gene_matriz_data.describe()

       Cromossomo
count     4.00000
mean     11.75000
std       4.99166
min       5.00000
25%      10.25000
50%      12.50000
75%      14.00000
max      17.00000

In [108]:
dir(gene_matriz_data)

['Cromossomo',
 'Organismo',
 'Origem',
 'T',
 'Tipo',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_add_numeric_operations',
 '_agg_by_level',
 '_agg_examples_doc',
 '_agg_summary_and_see_also_doc',
 '_align_frame',
 '_align_series',
 '_arith_method',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_from_arguments',
 '_construct_result',
 '_constructor',
 '_constructor_sliced',
 '_convert',
 '_count_level',
 '_data',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_join_compat',
 '_logical_func',
 '_logical_method',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_protect_consolidate',
 '_reduce',
 '_reindex_axes',
 '_reindex_columns',
 '_reindex_index',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isin',
 'isna',
 'isnull',
 'items',
 'iteritems',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lookup',
 'lt',
 'mad',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']