In [1]:
prim_num = 10.01
seg_num = 3

In [5]:
resul = prim_num ** seg_num
resul

1003.0030009999999

In [9]:
resul = round(prim_num / seg_num, 4)
resul

3.3367

In [10]:
round_dec = 3
tupla_opera = (
    prim_num + seg_num,
    prim_num - seg_num,
    prim_num * seg_num,
    round(prim_num / seg_num, round_dec),
    prim_num // seg_num,
    round(prim_num % seg_num, round_dec),
    round(prim_num ** seg_num, round_dec),
)
tupla_opera

(13.01, 7.01, 30.03, 3.337, 3.0, 1.01, 1003.003)

In [14]:
try:
    tupla_opera += 2
    tupla_opera
except:
    print('Erro')

Erro

In [16]:
tupla_opera += tupla_opera
tupla_opera

(13.01,
 7.01,
 30.03,
 3.337,
 3.0,
 1.01,
 1003.003,
 13.01,
 7.01,
 30.03,
 3.337,
 3.0,
 1.01,
 1003.003)

In [19]:
[1,2] + ['a','b'] + [False, True]

[1, 2, 'a', 'b', False, True]

In [23]:
tupla_opera *= 2
tupla_opera

(13.01,
 7.01,
 30.03,
 3.337,
 3.0,
 1.01,
 1003.003,
 13.01,
 7.01,
 30.03,
 3.337,
 3.0,
 1.01,
 1003.003,
 13.01,
 7.01,
 30.03,
 3.337,
 3.0,
 1.01,
 1003.003,
 13.01,
 7.01,
 30.03,
 3.337,
 3.0,
 1.01,
 1003.003)

In [28]:
tupla_opera[0] += 2
tupla_opera

TypeError: 'tuple' object does not support item assignment

In [31]:
lista_opera = list(tupla_opera[:7])
lista_opera

[13.01, 7.01, 30.03, 3.337, 3.0, 1.01, 1003.003]

In [32]:
lista_opera += 2

TypeError: 'int' object is not iterable

In [33]:
lista_opera += lista_opera
lista_opera

[13.01,
 7.01,
 30.03,
 3.337,
 3.0,
 1.01,
 1003.003,
 13.01,
 7.01,
 30.03,
 3.337,
 3.0,
 1.01,
 1003.003]

In [35]:
lista_opera *= 2
lista_opera

[13.01,
 7.01,
 30.03,
 3.337,
 3.0,
 1.01,
 1003.003,
 13.01,
 7.01,
 30.03,
 3.337,
 3.0,
 1.01,
 1003.003,
 13.01,
 7.01,
 30.03,
 3.337,
 3.0,
 1.01,
 1003.003,
 13.01,
 7.01,
 30.03,
 3.337,
 3.0,
 1.01,
 1003.003]

In [38]:
lista_opera[0] += 2
lista_opera

[15.01,
 7.01,
 30.03,
 3.337,
 3.0,
 1.01,
 1003.003,
 13.01,
 7.01,
 30.03,
 3.337,
 3.0,
 1.01,
 1003.003,
 13.01,
 7.01,
 30.03,
 3.337,
 3.0,
 1.01,
 1003.003,
 13.01,
 7.01,
 30.03,
 3.337,
 3.0,
 1.01,
 1003.003]

In [39]:
dic_opera = {
'Soma': prim_num + seg_num,
'Subt': prim_num - seg_num,
'Mult': prim_num * seg_num,
'Divi': round(prim_num / seg_num, round_dec),
'Inte': prim_num // seg_num,
'Rest': round(prim_num % seg_num, round_dec),
'Expo': round(prim_num ** seg_num, round_dec),
}
dic_opera

{'Soma': 13.01,
 'Subt': 7.01,
 'Mult': 30.03,
 'Divi': 3.337,
 'Inte': 3.0,
 'Rest': 1.01,
 'Expo': 1003.003}

In [48]:
dic_opera += dic_opera

TypeError: unsupported operand type(s) for +=: 'dict' and 'dict'

In [49]:
dic_opera *= dic_opera

TypeError: unsupported operand type(s) for *=: 'dict' and 'dict'

In [50]:
dic_opera

{'Soma': 13.01,
 'Subt': 7.01,
 'Mult': 30.03,
 'Divi': 3.337,
 'Inte': 3.0,
 'Rest': 1.01,
 'Expo': 1003.003}

In [51]:
dic_opera_2 = {
    'Somar': prim_num + seg_num,
    'Subtr': prim_num - seg_num,
    'Multip': prim_num * seg_num,
    'Dividir': round(prim_num / seg_num, round_dec),
    'Inteiro': prim_num // seg_num,
    'Resto': round(prim_num % seg_num, round_dec),
    'Expone': round(prim_num ** seg_num, round_dec),
}
dic_opera_2

{'Somar': 13.01,
 'Subtr': 7.01,
 'Multip': 30.03,
 'Dividir': 3.337,
 'Inteiro': 3.0,
 'Resto': 1.01,
 'Expone': 1003.003}

In [54]:
dic_opera_3 = {}
dic_opera_3.update(dic_opera)
dic_opera_3.update(dic_opera_2)
dic_opera_3

{'Soma': 13.01,
 'Subt': 7.01,
 'Mult': 30.03,
 'Divi': 3.337,
 'Inte': 3.0,
 'Rest': 1.01,
 'Expo': 1003.003,
 'Somar': 13.01,
 'Subtr': 7.01,
 'Multip': 30.03,
 'Dividir': 3.337,
 'Inteiro': 3.0,
 'Resto': 1.01,
 'Expone': 1003.003}

In [55]:
import numpy as np

In [61]:
array = np.asarray(lista_opera[-7:])
array

array([  13.01 ,    7.01 ,   30.03 ,    3.337,    3.   ,    1.01 ,
       1003.003])

In [62]:
array += 2
array

In [64]:
array -= 2
array

array([  13.01 ,    7.01 ,   30.03 ,    3.337,    3.   ,    1.01 ,
       1003.003])

In [65]:
array += array
array

array([  26.02 ,   14.02 ,   60.06 ,    6.674,    6.   ,    2.02 ,
       2006.006])

In [68]:
array = np.insert(arr=array, obj=len(array), values=array)
array

array([  26.02 ,   14.02 ,   60.06 ,    6.674,    6.   ,    2.02 ,
       2006.006,   26.02 ,   14.02 ,   60.06 ,    6.674,    6.   ,
          2.02 , 2006.006,   26.02 ,   14.02 ,   60.06 ,    6.674,
          6.   ,    2.02 , 2006.006,   26.02 ,   14.02 ,   60.06 ,
          6.674,    6.   ,    2.02 , 2006.006])

In [69]:
len(array)

28

In [70]:
array.shape

(28,)

In [71]:
array = array.reshape(4,7)
array

array([[  26.02 ,   14.02 ,   60.06 ,    6.674,    6.   ,    2.02 ,
        2006.006],
       [  26.02 ,   14.02 ,   60.06 ,    6.674,    6.   ,    2.02 ,
        2006.006],
       [  26.02 ,   14.02 ,   60.06 ,    6.674,    6.   ,    2.02 ,
        2006.006],
       [  26.02 ,   14.02 ,   60.06 ,    6.674,    6.   ,    2.02 ,
        2006.006]])

In [72]:
import pandas as pd

In [73]:
data_frame = pd.DataFrame(array.copy())
data_frame

       0      1      2      3    4     5         6
0  26.02  14.02  60.06  6.674  6.0  2.02  2006.006
1  26.02  14.02  60.06  6.674  6.0  2.02  2006.006
2  26.02  14.02  60.06  6.674  6.0  2.02  2006.006
3  26.02  14.02  60.06  6.674  6.0  2.02  2006.006

In [74]:
data_frame += 2
data_frame

       0      1      2      3    4     5         6
0  28.02  16.02  62.06  8.674  8.0  4.02  2008.006
1  28.02  16.02  62.06  8.674  8.0  4.02  2008.006
2  28.02  16.02  62.06  8.674  8.0  4.02  2008.006
3  28.02  16.02  62.06  8.674  8.0  4.02  2008.006

In [75]:
data_frame %= 2
data_frame

      0     1     2      3    4     5      6
0  0.02  0.02  0.06  0.674  0.0  0.02  0.006
1  0.02  0.02  0.06  0.674  0.0  0.02  0.006
2  0.02  0.02  0.06  0.674  0.0  0.02  0.006
3  0.02  0.02  0.06  0.674  0.0  0.02  0.006

In [79]:
data_frame * 2
data_frame

      0     1     2      3    4     5      6
0  0.02  0.02  0.06  0.674  0.0  0.02  0.006
1  0.02  0.02  0.06  0.674  0.0  0.02  0.006
2  0.02  0.02  0.06  0.674  0.0  0.02  0.006
3  0.02  0.02  0.06  0.674  0.0  0.02  0.006

In [82]:
data_frame += data_frame
data_frame

      0     1     2      3    4     5      6
0  0.08  0.08  0.24  2.696  0.0  0.08  0.024
1  0.08  0.08  0.24  2.696  0.0  0.08  0.024
2  0.08  0.08  0.24  2.696  0.0  0.08  0.024
3  0.08  0.08  0.24  2.696  0.0  0.08  0.024

In [86]:
data_frame += [1,2,3,4,5,6,7]
data_frame

      0     1     2      3    4     5      6
0  1.08  2.08  3.24  6.696  5.0  6.08  7.024
1  1.08  2.08  3.24  6.696  5.0  6.08  7.024
2  1.08  2.08  3.24  6.696  5.0  6.08  7.024
3  1.08  2.08  3.24  6.696  5.0  6.08  7.024

In [88]:
array = np.arange(start=-10, stop=10, step=0.5)
array

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [89]:
len(array)

40

In [90]:
array = array.reshape(8,5)
array

array([[-10. ,  -9.5,  -9. ,  -8.5,  -8. ],
       [ -7.5,  -7. ,  -6.5,  -6. ,  -5.5],
       [ -5. ,  -4.5,  -4. ,  -3.5,  -3. ],
       [ -2.5,  -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5,   2. ],
       [  2.5,   3. ,   3.5,   4. ,   4.5],
       [  5. ,   5.5,   6. ,   6.5,   7. ],
       [  7.5,   8. ,   8.5,   9. ,   9.5]])

In [91]:
data_frame = pd.DataFrame(array[:])
data_frame

      0    1    2    3    4
0 -10.0 -9.5 -9.0 -8.5 -8.0
1  -7.5 -7.0 -6.5 -6.0 -5.5
2  -5.0 -4.5 -4.0 -3.5 -3.0
3  -2.5 -2.0 -1.5 -1.0 -0.5
4   0.0  0.5  1.0  1.5  2.0
5   2.5  3.0  3.5  4.0  4.5
6   5.0  5.5  6.0  6.5  7.0
7   7.5  8.0  8.5  9.0  9.5

In [92]:
data_frame **= 2
data_frame

        0      1      2      3      4
0  100.00  90.25  81.00  72.25  64.00
1   56.25  49.00  42.25  36.00  30.25
2   25.00  20.25  16.00  12.25   9.00
3    6.25   4.00   2.25   1.00   0.25
4    0.00   0.25   1.00   2.25   4.00
5    6.25   9.00  12.25  16.00  20.25
6   25.00  30.25  36.00  42.25  49.00
7   56.25  64.00  72.25  81.00  90.25

In [93]:
data_frame **= 0.5
data_frame

      0    1    2    3    4
0  10.0  9.5  9.0  8.5  8.0
1   7.5  7.0  6.5  6.0  5.5
2   5.0  4.5  4.0  3.5  3.0
3   2.5  2.0  1.5  1.0  0.5
4   0.0  0.5  1.0  1.5  2.0
5   2.5  3.0  3.5  4.0  4.5
6   5.0  5.5  6.0  6.5  7.0
7   7.5  8.0  8.5  9.0  9.5

In [94]:
data_frame = pd.concat([data_frame, data_frame], axis=0)
data_frame

      0    1    2    3    4
0  10.0  9.5  9.0  8.5  8.0
1   7.5  7.0  6.5  6.0  5.5
2   5.0  4.5  4.0  3.5  3.0
3   2.5  2.0  1.5  1.0  0.5
4   0.0  0.5  1.0  1.5  2.0
5   2.5  3.0  3.5  4.0  4.5
6   5.0  5.5  6.0  6.5  7.0
7   7.5  8.0  8.5  9.0  9.5
0  10.0  9.5  9.0  8.5  8.0
1   7.5  7.0  6.5  6.0  5.5
2   5.0  4.5  4.0  3.5  3.0
3   2.5  2.0  1.5  1.0  0.5
4   0.0  0.5  1.0  1.5  2.0
5   2.5  3.0  3.5  4.0  4.5
6   5.0  5.5  6.0  6.5  7.0
7   7.5  8.0  8.5  9.0  9.5

In [95]:
data_frame = pd.concat([data_frame, data_frame], axis=1)
data_frame

      0    1    2    3    4     0    1    2    3    4
0  10.0  9.5  9.0  8.5  8.0  10.0  9.5  9.0  8.5  8.0
1   7.5  7.0  6.5  6.0  5.5   7.5  7.0  6.5  6.0  5.5
2   5.0  4.5  4.0  3.5  3.0   5.0  4.5  4.0  3.5  3.0
3   2.5  2.0  1.5  1.0  0.5   2.5  2.0  1.5  1.0  0.5
4   0.0  0.5  1.0  1.5  2.0   0.0  0.5  1.0  1.5  2.0
5   2.5  3.0  3.5  4.0  4.5   2.5  3.0  3.5  4.0  4.5
6   5.0  5.5  6.0  6.5  7.0   5.0  5.5  6.0  6.5  7.0
7   7.5  8.0  8.5  9.0  9.5   7.5  8.0  8.5  9.0  9.5
0  10.0  9.5  9.0  8.5  8.0  10.0  9.5  9.0  8.5  8.0
1   7.5  7.0  6.5  6.0  5.5   7.5  7.0  6.5  6.0  5.5
2   5.0  4.5  4.0  3.5  3.0   5.0  4.5  4.0  3.5  3.0
3   2.5  2.0  1.5  1.0  0.5   2.5  2.0  1.5  1.0  0.5
4   0.0  0.5  1.0  1.5  2.0   0.0  0.5  1.0  1.5  2.0
5   2.5  3.0  3.5  4.0  4.5   2.5  3.0  3.5  4.0  4.5
6   5.0  5.5  6.0  6.5  7.0   5.0  5.5  6.0  6.5  7.0
7   7.5  8.0  8.5  9.0  9.5   7.5  8.0  8.5  9.0  9.5

In [96]:
data_carc = ['a','b','c','d','e','f','g','h','i','j']
data_carc

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [98]:
data_frame.columns = data_carc
data_frame

      a    b    c    d    e     f    g    h    i    j
0  10.0  9.5  9.0  8.5  8.0  10.0  9.5  9.0  8.5  8.0
1   7.5  7.0  6.5  6.0  5.5   7.5  7.0  6.5  6.0  5.5
2   5.0  4.5  4.0  3.5  3.0   5.0  4.5  4.0  3.5  3.0
3   2.5  2.0  1.5  1.0  0.5   2.5  2.0  1.5  1.0  0.5
4   0.0  0.5  1.0  1.5  2.0   0.0  0.5  1.0  1.5  2.0
5   2.5  3.0  3.5  4.0  4.5   2.5  3.0  3.5  4.0  4.5
6   5.0  5.5  6.0  6.5  7.0   5.0  5.5  6.0  6.5  7.0
7   7.5  8.0  8.5  9.0  9.5   7.5  8.0  8.5  9.0  9.5
0  10.0  9.5  9.0  8.5  8.0  10.0  9.5  9.0  8.5  8.0
1   7.5  7.0  6.5  6.0  5.5   7.5  7.0  6.5  6.0  5.5
2   5.0  4.5  4.0  3.5  3.0   5.0  4.5  4.0  3.5  3.0
3   2.5  2.0  1.5  1.0  0.5   2.5  2.0  1.5  1.0  0.5
4   0.0  0.5  1.0  1.5  2.0   0.0  0.5  1.0  1.5  2.0
5   2.5  3.0  3.5  4.0  4.5   2.5  3.0  3.5  4.0  4.5
6   5.0  5.5  6.0  6.5  7.0   5.0  5.5  6.0  6.5  7.0
7   7.5  8.0  8.5  9.0  9.5   7.5  8.0  8.5  9.0  9.5

In [100]:
len(data_frame.index)

16

In [103]:
data_frame.index = np.arange(len(data_frame.index))+10
data_frame

       a    b    c    d    e     f    g    h    i    j
10  10.0  9.5  9.0  8.5  8.0  10.0  9.5  9.0  8.5  8.0
11   7.5  7.0  6.5  6.0  5.5   7.5  7.0  6.5  6.0  5.5
12   5.0  4.5  4.0  3.5  3.0   5.0  4.5  4.0  3.5  3.0
13   2.5  2.0  1.5  1.0  0.5   2.5  2.0  1.5  1.0  0.5
14   0.0  0.5  1.0  1.5  2.0   0.0  0.5  1.0  1.5  2.0
15   2.5  3.0  3.5  4.0  4.5   2.5  3.0  3.5  4.0  4.5
16   5.0  5.5  6.0  6.5  7.0   5.0  5.5  6.0  6.5  7.0
17   7.5  8.0  8.5  9.0  9.5   7.5  8.0  8.5  9.0  9.5
18  10.0  9.5  9.0  8.5  8.0  10.0  9.5  9.0  8.5  8.0
19   7.5  7.0  6.5  6.0  5.5   7.5  7.0  6.5  6.0  5.5
20   5.0  4.5  4.0  3.5  3.0   5.0  4.5  4.0  3.5  3.0
21   2.5  2.0  1.5  1.0  0.5   2.5  2.0  1.5  1.0  0.5
22   0.0  0.5  1.0  1.5  2.0   0.0  0.5  1.0  1.5  2.0
23   2.5  3.0  3.5  4.0  4.5   2.5  3.0  3.5  4.0  4.5
24   5.0  5.5  6.0  6.5  7.0   5.0  5.5  6.0  6.5  7.0
25   7.5  8.0  8.5  9.0  9.5   7.5  8.0  8.5  9.0  9.5

In [105]:
data_frame['e']

10    8.0
11    5.5
12    3.0
13    0.5
14    2.0
15    4.5
16    7.0
17    9.5
18    8.0
19    5.5
20    3.0
21    0.5
22    2.0
23    4.5
24    7.0
25    9.5
Name: e, dtype: float64

In [107]:
data_frame['j'] = data_frame['e'] / data_frame['a']

data_frame

       a    b    c    d    e     f    g    h    i         j
10  10.0  9.5  9.0  8.5  8.0  10.0  9.5  9.0  8.5  0.800000
11   7.5  7.0  6.5  6.0  5.5   7.5  7.0  6.5  6.0  0.733333
12   5.0  4.5  4.0  3.5  3.0   5.0  4.5  4.0  3.5  0.600000
13   2.5  2.0  1.5  1.0  0.5   2.5  2.0  1.5  1.0  0.200000
14   0.0  0.5  1.0  1.5  2.0   0.0  0.5  1.0  1.5       inf
15   2.5  3.0  3.5  4.0  4.5   2.5  3.0  3.5  4.0  1.800000
16   5.0  5.5  6.0  6.5  7.0   5.0  5.5  6.0  6.5  1.400000
17   7.5  8.0  8.5  9.0  9.5   7.5  8.0  8.5  9.0  1.266667
18  10.0  9.5  9.0  8.5  8.0  10.0  9.5  9.0  8.5  0.800000
19   7.5  7.0  6.5  6.0  5.5   7.5  7.0  6.5  6.0  0.733333
20   5.0  4.5  4.0  3.5  3.0   5.0  4.5  4.0  3.5  0.600000
21   2.5  2.0  1.5  1.0  0.5   2.5  2.0  1.5  1.0  0.200000
22   0.0  0.5  1.0  1.5  2.0   0.0  0.5  1.0  1.5       inf
23   2.5  3.0  3.5  4.0  4.5   2.5  3.0  3.5  4.0  1.800000
24   5.0  5.5  6.0  6.5  7.0   5.0  5.5  6.0  6.5  1.400000
25   7.5  8.0  8.5  9.0  9.5   7.5  8.0  8.5  9.0  1.266667

In [108]:
data_frame.drop('j', axis=1, inplace=True)
data_frame

       a    b    c    d    e     f    g    h    i
10  10.0  9.5  9.0  8.5  8.0  10.0  9.5  9.0  8.5
11   7.5  7.0  6.5  6.0  5.5   7.5  7.0  6.5  6.0
12   5.0  4.5  4.0  3.5  3.0   5.0  4.5  4.0  3.5
13   2.5  2.0  1.5  1.0  0.5   2.5  2.0  1.5  1.0
14   0.0  0.5  1.0  1.5  2.0   0.0  0.5  1.0  1.5
15   2.5  3.0  3.5  4.0  4.5   2.5  3.0  3.5  4.0
16   5.0  5.5  6.0  6.5  7.0   5.0  5.5  6.0  6.5
17   7.5  8.0  8.5  9.0  9.5   7.5  8.0  8.5  9.0
18  10.0  9.5  9.0  8.5  8.0  10.0  9.5  9.0  8.5
19   7.5  7.0  6.5  6.0  5.5   7.5  7.0  6.5  6.0
20   5.0  4.5  4.0  3.5  3.0   5.0  4.5  4.0  3.5
21   2.5  2.0  1.5  1.0  0.5   2.5  2.0  1.5  1.0
22   0.0  0.5  1.0  1.5  2.0   0.0  0.5  1.0  1.5
23   2.5  3.0  3.5  4.0  4.5   2.5  3.0  3.5  4.0
24   5.0  5.5  6.0  6.5  7.0   5.0  5.5  6.0  6.5
25   7.5  8.0  8.5  9.0  9.5   7.5  8.0  8.5  9.0

In [109]:
data_frame['j'] = data_frame['e'] / data_frame['b']
data_frame

       a    b    c    d    e     f    g    h    i         j
10  10.0  9.5  9.0  8.5  8.0  10.0  9.5  9.0  8.5  0.842105
11   7.5  7.0  6.5  6.0  5.5   7.5  7.0  6.5  6.0  0.785714
12   5.0  4.5  4.0  3.5  3.0   5.0  4.5  4.0  3.5  0.666667
13   2.5  2.0  1.5  1.0  0.5   2.5  2.0  1.5  1.0  0.250000
14   0.0  0.5  1.0  1.5  2.0   0.0  0.5  1.0  1.5  4.000000
15   2.5  3.0  3.5  4.0  4.5   2.5  3.0  3.5  4.0  1.500000
16   5.0  5.5  6.0  6.5  7.0   5.0  5.5  6.0  6.5  1.272727
17   7.5  8.0  8.5  9.0  9.5   7.5  8.0  8.5  9.0  1.187500
18  10.0  9.5  9.0  8.5  8.0  10.0  9.5  9.0  8.5  0.842105
19   7.5  7.0  6.5  6.0  5.5   7.5  7.0  6.5  6.0  0.785714
20   5.0  4.5  4.0  3.5  3.0   5.0  4.5  4.0  3.5  0.666667
21   2.5  2.0  1.5  1.0  0.5   2.5  2.0  1.5  1.0  0.250000
22   0.0  0.5  1.0  1.5  2.0   0.0  0.5  1.0  1.5  4.000000
23   2.5  3.0  3.5  4.0  4.5   2.5  3.0  3.5  4.0  1.500000
24   5.0  5.5  6.0  6.5  7.0   5.0  5.5  6.0  6.5  1.272727
25   7.5  8.0  8.5  9.0  9.5   7.5  8.0  8.5  9.0  1.187500

In [115]:
data_frame = round(data_frame, 2)
data_frame

       a    b    c    d    e     f    g    h    i     j
10  10.0  9.5  9.0  8.5  8.0  10.0  9.5  9.0  8.5  0.84
11   7.5  7.0  6.5  6.0  5.5   7.5  7.0  6.5  6.0  0.79
12   5.0  4.5  4.0  3.5  3.0   5.0  4.5  4.0  3.5  0.67
13   2.5  2.0  1.5  1.0  0.5   2.5  2.0  1.5  1.0  0.25
14   0.0  0.5  1.0  1.5  2.0   0.0  0.5  1.0  1.5  4.00
15   2.5  3.0  3.5  4.0  4.5   2.5  3.0  3.5  4.0  1.50
16   5.0  5.5  6.0  6.5  7.0   5.0  5.5  6.0  6.5  1.27
17   7.5  8.0  8.5  9.0  9.5   7.5  8.0  8.5  9.0  1.19
18  10.0  9.5  9.0  8.5  8.0  10.0  9.5  9.0  8.5  0.84
19   7.5  7.0  6.5  6.0  5.5   7.5  7.0  6.5  6.0  0.79
20   5.0  4.5  4.0  3.5  3.0   5.0  4.5  4.0  3.5  0.67
21   2.5  2.0  1.5  1.0  0.5   2.5  2.0  1.5  1.0  0.25
22   0.0  0.5  1.0  1.5  2.0   0.0  0.5  1.0  1.5  4.00
23   2.5  3.0  3.5  4.0  4.5   2.5  3.0  3.5  4.0  1.50
24   5.0  5.5  6.0  6.5  7.0   5.0  5.5  6.0  6.5  1.27
25   7.5  8.0  8.5  9.0  9.5   7.5  8.0  8.5  9.0  1.19

In [117]:
data_frame.loc[[13,23]]

      a    b    c    d    e    f    g    h    i     j
13  2.5  2.0  1.5  1.0  0.5  2.5  2.0  1.5  1.0  0.25
23  2.5  3.0  3.5  4.0  4.5  2.5  3.0  3.5  4.0  1.50

In [119]:
data_frame_sum = data_frame.loc[13] + data_frame.loc[23]
data_frame_sum

a    5.00
b    5.00
c    5.00
d    5.00
e    5.00
f    5.00
g    5.00
h    5.00
i    5.00
j    1.75
dtype: float64

In [123]:
data_frame.iloc[-1]

a    7.50
b    8.00
c    8.50
d    9.00
e    9.50
f    7.50
g    8.00
h    8.50
i    9.00
j    1.19
Name: 25, dtype: float64

In [124]:
data_frame = data_frame.append(data_frame_sum, ignore_index=True)
data_frame

       a    b    c    d    e     f    g    h    i     j
0   10.0  9.5  9.0  8.5  8.0  10.0  9.5  9.0  8.5  0.84
1    7.5  7.0  6.5  6.0  5.5   7.5  7.0  6.5  6.0  0.79
2    5.0  4.5  4.0  3.5  3.0   5.0  4.5  4.0  3.5  0.67
3    2.5  2.0  1.5  1.0  0.5   2.5  2.0  1.5  1.0  0.25
4    0.0  0.5  1.0  1.5  2.0   0.0  0.5  1.0  1.5  4.00
5    2.5  3.0  3.5  4.0  4.5   2.5  3.0  3.5  4.0  1.50
6    5.0  5.5  6.0  6.5  7.0   5.0  5.5  6.0  6.5  1.27
7    7.5  8.0  8.5  9.0  9.5   7.5  8.0  8.5  9.0  1.19
8   10.0  9.5  9.0  8.5  8.0  10.0  9.5  9.0  8.5  0.84
9    7.5  7.0  6.5  6.0  5.5   7.5  7.0  6.5  6.0  0.79
10   5.0  4.5  4.0  3.5  3.0   5.0  4.5  4.0  3.5  0.67
11   2.5  2.0  1.5  1.0  0.5   2.5  2.0  1.5  1.0  0.25
12   0.0  0.5  1.0  1.5  2.0   0.0  0.5  1.0  1.5  4.00
13   2.5  3.0  3.5  4.0  4.5   2.5  3.0  3.5  4.0  1.50
14   5.0  5.5  6.0  6.5  7.0   5.0  5.5  6.0  6.5  1.27
15   7.5  8.0  8.5  9.0  9.5   7.5  8.0  8.5  9.0  1.19
16   5.0  5.0  5.0  5.0  5.0   5.0  5.0  5.0  5.0  1.75

In [126]:
data_frame.index = np.arange(len(data_frame.index))+10
data_frame

       a    b    c    d    e     f    g    h    i     j
10  10.0  9.5  9.0  8.5  8.0  10.0  9.5  9.0  8.5  0.84
11   7.5  7.0  6.5  6.0  5.5   7.5  7.0  6.5  6.0  0.79
12   5.0  4.5  4.0  3.5  3.0   5.0  4.5  4.0  3.5  0.67
13   2.5  2.0  1.5  1.0  0.5   2.5  2.0  1.5  1.0  0.25
14   0.0  0.5  1.0  1.5  2.0   0.0  0.5  1.0  1.5  4.00
15   2.5  3.0  3.5  4.0  4.5   2.5  3.0  3.5  4.0  1.50
16   5.0  5.5  6.0  6.5  7.0   5.0  5.5  6.0  6.5  1.27
17   7.5  8.0  8.5  9.0  9.5   7.5  8.0  8.5  9.0  1.19
18  10.0  9.5  9.0  8.5  8.0  10.0  9.5  9.0  8.5  0.84
19   7.5  7.0  6.5  6.0  5.5   7.5  7.0  6.5  6.0  0.79
20   5.0  4.5  4.0  3.5  3.0   5.0  4.5  4.0  3.5  0.67
21   2.5  2.0  1.5  1.0  0.5   2.5  2.0  1.5  1.0  0.25
22   0.0  0.5  1.0  1.5  2.0   0.0  0.5  1.0  1.5  4.00
23   2.5  3.0  3.5  4.0  4.5   2.5  3.0  3.5  4.0  1.50
24   5.0  5.5  6.0  6.5  7.0   5.0  5.5  6.0  6.5  1.27
25   7.5  8.0  8.5  9.0  9.5   7.5  8.0  8.5  9.0  1.19
26   5.0  5.0  5.0  5.0  5.0   5.0  5.0  5.0  5.0  1.75

In [132]:
data_nan = pd.DataFrame(
    data=np.nan,
    index=['index'],
    columns=np.arange(10)
)
data_nan

        0   1   2   3   4   5   6   7   8   9
index NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN

In [136]:
data_frame = data_frame.append(data_nan, ignore_index=True)
data_frame

,a,b,c,d,e,f,g,h,i,j,0,1,2,3,4,5,6,7,8,9
0,10.0,9.5,9.0,8.5,8.0,10.0,9.5,9.0,8.5,0.84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,7.5,7.0,6.5,6.0,5.5,7.5,7.0,6.5,6.0,0.79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5.0,4.5,4.0,3.5,3.0,5.0,4.5,4.0,3.5,0.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2.5,2.0,1.5,1.0,0.5,2.5,2.0,1.5,1.0,0.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.0,0.5,1.0,1.5,2.0,0.0,0.5,1.0,1.5,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2.5,3.0,3.5,4.0,4.5,2.5,3.0,3.5,4.0,1.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,5.0,5.5,6.0,6.5,7.0,5.0,5.5,6.0,6.5,1.27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7.5,8.0,8.5,9.0,9.5,7.5,8.0,8.5,9.0,1.19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,10.0,9.5,9.0,8.5,8.0,10.0,9.5,9.0,8.5,0.84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,7.5,7.0,6.5,6.0,5.5,7.5,7.0,6.5,6.0,0.79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,5.0,4.5,4.0,3.5,3.0,5.0,4.5,4.0,3.5,0.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2.5,2.0,1.5,1.0,0.5,2.5,2.0,1.5,1.0,0.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,0.0,0.5,1.0,1.5,2.0,0.0,0.5,1.0,1.5,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2.5,3.0,3.5,4.0,4.5,2.5,3.0,3.5,4.0,1.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,5.0,5.5,6.0,6.5,7.0,5.0,5.5,6.0,6.5,1.27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,7.5,8.0,8.5,9.0,9.5,7.5,8.0,8.5,9.0,1.19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,1.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN