In [20]:
import numpy as np
import pandas as pd

In [24]:
obj_array = np.arange(start=-10, stop=10, step=0.5).reshape(5,8)
obj_array

array([[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5,   4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,   9.5]])

In [43]:
obj_lista1 = list(obj_array[1])
obj_lista2 = obj_lista1[:]
obj_lista1

[-6.0, -5.5, -5.0, -4.5, -4.0, -3.5, -3.0, -2.5]

In [44]:
obj_lista2

[-6.0, -5.5, -5.0, -4.5, -4.0, -3.5, -3.0, -2.5]

In [45]:
obj_lista1.append(1000)
obj_lista2

[-6.0, -5.5, -5.0, -4.5, -4.0, -3.5, -3.0, -2.5]

In [46]:
obj_lista1 == obj_lista2

False

In [47]:
obj_lista1 is obj_lista2

False

In [48]:
obj_lista1 is not obj_lista2

True

In [50]:
obj_lista1

[-6.0, -5.5, -5.0, -4.5, -4.0, -3.5, -3.0, -2.5, 1000]

In [51]:
1000 in obj_lista1

True

In [53]:
1000 not in obj_lista1

False

In [54]:
obj_lista2

[-6.0, -5.5, -5.0, -4.5, -4.0, -3.5, -3.0, -2.5]

In [55]:
1000 in obj_lista2

False

In [56]:
1000 not in obj_lista2

True

In [57]:
obj_array

array([[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5,   4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,   9.5]])

In [58]:
1000 in obj_array

False

In [60]:
9.5 in obj_array

True

In [61]:
9.5 not in obj_array

False

In [68]:
True and True and True and True

True

In [70]:
False or False or False or False

False

In [79]:
obj_lista1 == obj_lista2 and obj_lista2 == obj_lista2 and obj_lista1 == obj_lista1

False

In [80]:
obj_lista1 == obj_lista2 or obj_lista2 == obj_lista2 or obj_lista1 == obj_lista1

True

In [81]:
obj_lista1 == obj_lista2 and not obj_lista2 == obj_lista2 and not obj_lista1 == obj_lista1

False

In [82]:
obj_lista1 == obj_lista2 or not obj_lista2 == obj_lista2 or not obj_lista1 == obj_lista1

False

In [83]:
not obj_lista1 == obj_lista2 and obj_lista2 == obj_lista2 and obj_lista1 == obj_lista1

True

In [92]:
# and
np.all([True, True, True, True])

True

In [93]:
# and
np.all([True, False, True, True])

False

In [99]:
# and
np.all([obj_array[0] == obj_array[-1], obj_array[0] == obj_array[-2]])

False

In [102]:
# or
np.any([
    obj_array[0] == obj_array[0],
    obj_array[0] == obj_array[1],
    obj_array[0] == obj_array[2],
])

True

In [103]:
# and
np.all([
    obj_array[0] == obj_array[0],
    obj_array[0] == obj_array[1],
    obj_array[0] == obj_array[2],
])

False

In [104]:
obj_data = pd.DataFrame(obj_array)
obj_data

      0    1    2    3    4    5    6    7
0 -10.0 -9.5 -9.0 -8.5 -8.0 -7.5 -7.0 -6.5
1  -6.0 -5.5 -5.0 -4.5 -4.0 -3.5 -3.0 -2.5
2  -2.0 -1.5 -1.0 -0.5  0.0  0.5  1.0  1.5
3   2.0  2.5  3.0  3.5  4.0  4.5  5.0  5.5
4   6.0  6.5  7.0  7.5  8.0  8.5  9.0  9.5

In [108]:
np.all([obj_data[0] == obj_data[0], obj_data[0] == obj_data[0]])

True

In [110]:
np.any([obj_data[1] == obj_data[0], obj_data[0] == obj_data[0]])

True

In [116]:
obj_data >= -3

       0      1      2      3      4      5      6      7
0  False  False  False  False  False  False  False  False
1  False  False  False  False  False  False   True   True
2   True   True   True   True   True   True   True   True
3   True   True   True   True   True   True   True   True
4   True   True   True   True   True   True   True   True

In [117]:
obj_data[obj_data >= -3]

     0    1    2    3    4    5    6    7
0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1  NaN  NaN  NaN  NaN  NaN  NaN -3.0 -2.5
2 -2.0 -1.5 -1.0 -0.5  0.0  0.5  1.0  1.5
3  2.0  2.5  3.0  3.5  4.0  4.5  5.0  5.5
4  6.0  6.5  7.0  7.5  8.0  8.5  9.0  9.5

In [121]:
# and = &
# or = |
# , = ()
obj_data[
    (obj_data >= 4) |
    (obj_data <= -4)
]

      0    1    2    3    4    5    6    7
0 -10.0 -9.5 -9.0 -8.5 -8.0 -7.5 -7.0 -6.5
1  -6.0 -5.5 -5.0 -4.5 -4.0  NaN  NaN  NaN
2   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3   NaN  NaN  NaN  NaN  4.0  4.5  5.0  5.5
4   6.0  6.5  7.0  7.5  8.0  8.5  9.0  9.5

In [125]:
# and = &
# or = |
# , = ()
obj_data[
    (obj_data <= 4) &
    (obj_data >= -4)
]

     0    1    2    3    4    5    6    7
0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1  NaN  NaN  NaN  NaN -4.0 -3.5 -3.0 -2.5
2 -2.0 -1.5 -1.0 -0.5  0.0  0.5  1.0  1.5
3  2.0  2.5  3.0  3.5  4.0  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

In [126]:
# and = &
# or = |
# , = ()
obj_data[
    (obj_data <= 4) &
    (obj_data >= -4)
].loc[1]

0    NaN
1    NaN
2    NaN
3    NaN
4   -4.0
5   -3.5
6   -3.0
7   -2.5
Name: 1, dtype: float64

In [127]:
# and = &
# or = |
# , = ()
obj_data[
    (obj_data <= 4) &
    (obj_data >= -4)
][1]

0    NaN
1    NaN
2   -1.5
3    2.5
4    NaN
Name: 1, dtype: float64

In [128]:
# and = &
# or = |
# , = ()
obj_data[
    (obj_data <= 4) &
    (obj_data >= -4)
][[1,3]]

     1    3
0  NaN  NaN
1  NaN  NaN
2 -1.5 -0.5
3  2.5  3.5
4  NaN  NaN

In [131]:
# and = &
# or = |
# , = ()
obj_data[
    (obj_data <= 4) &
    (obj_data >= -4)
].loc[1:4]

     0    1    2    3    4    5    6    7
1  NaN  NaN  NaN  NaN -4.0 -3.5 -3.0 -2.5
2 -2.0 -1.5 -1.0 -0.5  0.0  0.5  1.0  1.5
3  2.0  2.5  3.0  3.5  4.0  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

In [132]:
# and = &
# or = |
# , = ()
obj_data[
    (obj_data <= 4) &
    (obj_data >= -4)
].loc[1:4][[1,3,6]]

     1    3    6
1  NaN  NaN -3.0
2 -1.5 -0.5  1.0
3  2.5  3.5  NaN
4  NaN  NaN  NaN